# Generated by Django 3.2 on 2024-12-09 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_cartitem_genre_manga_mangaimage_order_orderitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='sinopsis',
            field=models.TextField(default='', verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(verbose_name='Descripcion articulo'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(related_name='Generos', to='libreria.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas_for_sale', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Subido en'),
        ),
    ]
