# Generated by Django 3.2 on 2024-12-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20241209_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaimage',
            name='image',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
